In [13]:
import numpy as np
from muFFT import FFT

fft = FFT((12, 13, 14))

In [16]:
arr = np.ones((12, 13, 14))
farr = fft.fft(arr)

fft.ifft(farr) * fft.normalisation

array([[[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]],

       [[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]],

       [[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]],

       ...,

       [[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1.

In [17]:
fft.coords.shape

(3, 12, 13, 14)

In [19]:
fft.fftfreq[1, 0, :, 0]

array([ 0.        ,  0.07692308,  0.15384615,  0.23076923,  0.30769231,
        0.38461538,  0.46153846, -0.46153846, -0.38461538, -0.30769231,
       -0.23076923, -0.15384615, -0.07692308])

In [25]:
# fftfreq  q

fft1 = FFT((13,))
arr = np.ones((fft1.nb_subdomain_grid_pts))
farr = fft1.fft(arr)

farr

array([ 1.30000000e+01+0.j, -4.44089210e-16+0.j,  2.22044605e-16+0.j,
       -2.22044605e-16+0.j,  2.22044605e-16+0.j,  1.11022302e-16+0.j,
        0.00000000e+00+0.j])